### ISSUE TITLE
banner not added dynamically

### ISSUE THREAD

**Issue by hatsch** [inaes-tic/mbc-etiquette#1]
when adding a banner nothing happens on the filter side ( melt output)
only when i close melt, and start it again ( ./mlt_dynamic_filter ) the previous added banner shows up.

the same is true now for adding images, which was working instantly with a previous version.

**Comment by jmrunge** [comment]
Can you give me mlt/melt & webvfx version and type of install (git, apt-get)?  It is working as expected with mlt 0.9.0 built from source with @ddennedy melted install script (http://www.mltframework.org/bin/view/MLT/BuildScripts) and latest webvfx.

**Comment by hatsch** [comment]
ok, i have MLT 0.9.1 from 16. july, but i am compiling 0.9 at the moment also with the MLT build scripts.
which repository are you using for webvfx?

there is the original repo: https://github.com/rectalogic/webvfx

and an updated version from @ddennedy with some enhancements (mostly for transparency and qt5 build fixes) https://github.com/ddennedy/webvfx

in my last test i was using the original repository..

btw: the visual editor branch looks awesome!

**Comment by jmrunge** [comment]
Im using original repo too (didnt know about @ddennedy's repo!).  If
testing with 0.9.0 still does not work, you may want to enable 'debug'.
For this, you should comment visibility and display properties of #banner
rule in lines 21 and 22 of dynamic-filter.html.

2013/9/4 hatsch notifications@github.com

**Comment by hatsch** [comment]
testing with 0.9.0 and rectalogics repo still shows the same behaviour..
only restarting the melt process shows the previously added banner/image

this  happens with both. master and visual-editor-test branch.

when commenting lines 21,22 in dynamic-filter.html 
the banner in the bottom says: Error - Status: Internal Server Error
so that's probably the issue?

i have node 0.8.25 installed

**Comment by jmrunge** [comment]
I use node 0.10... But it should work... Whats your CPU and RAM?

-----Original Message-----

**Comment by hatsch** [comment]
Intel(R) Core(TM) i7-2677M CPU @ 1.80GHz
with 4GB of RAM

**Comment by hatsch** [comment]
seems to be sufficent, 
node and melt don't seem to consume too much..

i've also tried with ddennedy and rectalogic WEBVFX

just trying out at which commit, it stopped working..

**Comment by hatsch** [comment]
the behaviour starts with 2f603e687da71831be1507039be5b309ef6300cc
so when the banner was added...

previous versions just update the filter instantly

**Comment by hatsch** [comment]
same thing with node v0.10.17

**Comment by hatsch** [comment]
after installing node 0.10 AND running npm update
it works now again...
strange

**Comment by hatsch** [comment]
also update video in visual-editor works now as expected..

and what's really strange is that it now even works with node 0.8

sorry for the noise! but i can't find what i have done different now...

**Comment by jmrunge** [comment]
Seems like some way your express instalation went corrupted... The main change in the commit you pointed out was that instead of using setTimeout to query the express server I started using the render event of webVFX.  This shouldnt have any effects on the express server, but... strangest things had happened! :)
Glad it started working again! :)
