### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by abhayamicro** [inaes-tic/mbc-etiquette#62]
I want to use [Sourcegraph](https://sourcegraph.com) for mbc-etiquette code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/inaes-tic/mbc-etiquette. (It should only take 30 seconds.)

Thank you!

**Comment by pardo-bsso** [comment]
Done .
