### ISSUE TITLE
Reuse uploaded images

### ISSUE THREAD

**Issue by josx** [inaes-tic/mbc-etiquette#7]
Right now We cant use uploaded images in different sketches.
we can use a watch over uploaded  dir to show up on editor and let the user select.
(like it was on legacy forms done by @jmrunge )

Please check it here.
https://github.com/inaes-tic/webvfx-dynamic-filters/commit/df311fcb9e6151811edecacf531f212fab930621

**Comment by jmrunge** [comment]
In my legacy forms, there were separated actions for uploading images and for using them in the editor... I think this is the way it should be, most of the time the user will be using an image that is already uploaded to the server.  And the watch was for giving the user the change to copy images directly into one dir and avoid using the upload function (if using it from the server itself).
